perf: use map to dedupe fetch requests
AlaskaAirlines/auro-icon pull request #14
Opened 2020-11-28 21:40 UTC by littleninja

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Partially Fixes:** #13 

## Summary:

We often use JavaScript to fetch and inline SVGs (if I'm reading the history right, the SVG 2.0 spec missed an iteration in web development that brought us CORS). When an `img[src]` is used several times on a page, the browser makes a single network request and resolves the image source to each instance. The same is not true for Fetch API. By adding a minimal map, we're simulating this browser behavior and preventing excessive network calls for icon SVGs.

Before:
<img width="1103" alt="Screen Shot 2020-11-28 at 12 33 41 PM" src="https://user-images.githubusercontent.com/4391579/100526575-e99db800-317e-11eb-9bb1-3258739e2709.png">

After:
<img width="1110" alt="Screen Shot 2020-11-28 at 1 13 27 PM" src="https://user-images.githubusercontent.com/4391579/100526574-e7d3f480-317e-11eb-8861-142c1899a4fa.png">

## Type of change:

- [x] Revision of an existing capability

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2020-11-28 21:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/AlaskaAirlines/auro-icon?pullRequest=14) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/AlaskaAirlines/auro-icon?pullRequest=14) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AlaskaAirlines/auro-icon?pullRequest=14) it.</sub>

2020-12-02 16:03 UTC, geoffrich submitted a review, later dismissed
Looks great!

2020-12-02 17:40 UTC, blackfalcon requested changes
This is top-shelf work! Thanks for the update!

The only ask is that you update the commit prefix from `perf` to `fix`. Since this is a single update that is not coupled with another commit that will trigger a version release. 

I'd suggest something like, 

`fix: add performance update ... ` or something to that effect. 

Thanks!

2020-12-02 18:21 UTC, littleninja commented
Thanks for the feedback @blackfalcon! Revised the pull request title to address your point about semantic versioning. If you need to nudge it further, I _think_ I set the option for target branch maintainers to have edit permissions.

2020-12-02 20:07 UTC, littleninja commented on test/auro-icon.test.js
> +  it ('does not duplicate requests for same icon source', async () => {
Oops, removing extra space between test function and opening paren.

```suggestion
  it('does not duplicate requests for same icon source', async () => {
```

2020-12-02 21:54 UTC, blackfalcon approved these changes

2020-12-02 21:56 UTC, merged

2020-12-02 23:01 UTC, ecommerceUXdesign commented
:tada: This PR is included in version 2.0.3 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@alaskaairux/auro-icon/v/2.0.3)
- [GitHub release](https://github.com/AlaskaAirlines/auro-icon/releases/tag/v2.0.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: