Add new aria-hidden toggle
AlaskaAirlines/auro-icon pull request #56
Opened 2022-12-21 04:30 UTC by blackfalcon

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Resolves:** #54 

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

The scope of this update is to include a new `ariaHidden` attribute that will allow users to remove the default `aria-hidden="true"` value. 

Other updates outlined in commits include updates to dependencies, demo HTML text support, and Github actions workflow dependency updates. 

## Type of change:

Please delete options that are not relevant.

- [x] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2022-12-26 19:16 UTC, blackfalcon commented
The CODEOWNERS file was never processed for this PR and I had to manually add it. Not sure why that happened, but the result was that the PR fell through the cracks and was not addressed in a timely manner.

2022-12-27 18:26 UTC, jason-capsule42 requested changes

2022-12-27 18:26 UTC, jason-capsule42 commented on src/auro-icon.js
> + * @attr {String} title - Set custom description of icon in use.
This should be removed.

2022-12-27 18:26 UTC, jason-capsule42 commented on src/auro-icon.js
> +        reflect: true
Also delete this
```suggestion
```

2022-12-28 00:08 UTC, blackfalcon commented on demo/demo.md
> +  <auro-icon label category="in-flight" name="wifi">Your flight is enabled with super fast Wi-Fi</auro-icon>
Addressed

2022-12-28 00:09 UTC, blackfalcon commented on src/auro-icon.js
> +        reflect: true
removed

2022-12-28 00:09 UTC, blackfalcon commented on src/auro-icon.js
> + * @attr {String} title - Set custom description of icon in use.
removed

2022-12-28 17:01 UTC, jason-capsule42 approved these changes

2022-12-28 17:01 UTC, merged

2022-12-28 17:04 UTC, AuroDesignSystem commented
:tada: This PR is included in version 3.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@alaskaairux/auro-icon/v/3.3.0)
- [GitHub release](https://github.com/AlaskaAirlines/auro-icon/releases/tag/v3.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: